export enum EnumTableColum {
    ID = "id",
    NAME = "name",
    IMAGE = "image",
    PRICE = "price",
    DESCRIPTION = "description",
    CATEGORY = "category",
    CATEGORY_ID = "category.id",
    CATEGORY_NAME = "category.name",
    EMAIL = "email", // ✅ fixed capitalization,
    ROLE = "role",
    TITLE = "title",
    RATING = "rating",
    DURATION = "duration",
    GENRE = "genre",
    RELEASE_DATE = "releaseDate",
    STATUS = "status",
    CREATED_AT = "created_at",
    ALT = 'alt',
    ADDRESS = "address",
    PHONE = "phone",
    HOURS="hours",
    VALID_UNTIL = "validUntil",
    DISCOUNT = "discount",
    ACTIVE="active",
    BOOKING="booking",
    ORDER="order",
    LINK = "link",
    DATE_SHOWING = "date_showing",
    CINEMA = "cinema",
    CINEMA_NAME = "cinema.name",
    CINEMA_ID = "cinema.id",
    DIRECTOR='director',
    CAST="cast",
    SYNOPSIS="synopsis",
    TRAILER="trailer",
    FILE='file',
    MOVIE_STATUS = "movie_status",
}
export enum EnumSupabseColumn{
    CINEMA_ID = "cinema_id",
    MOVIE_STATUS_ID = "movie_status_id",
}